<!doctype html>
<html lang="en">
    <head>
        
        <meta charset="UTF-8"/>
        <title>ZF2 angular</title>
        
        <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
        
    </head>
    <body ng-app="myApp">
        
        
        
        
        <!-- Wrap all page content here -->
<div id="wrap">

    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        
        
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Junao Oaks</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#/categorias">Categorias</a></li>
                    <li><a href="#/produtos">Produtos</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
        
<?= $this->content; ?>
        
 <div id="footer">
        <div class="container">
            <p class="text-muted credit">Junao Oaks.</p>
        </div>
    </div>
        
        
        
        
        
<!--        <div ng-controller="CtrlApp">
            <input type="text" ng-model="nome">
            <h1>{{nome}}</h1>
        </div>-->
        <script src="angular-1.3.13/angular.min.js"></script>
        <script src="angular-1.3.13/angular-route.min.js"></script>
        <script src="angular-1.3.13/angular-resource.min.js"></script>
        <script src="appangular/app.js"></script>
        <script src="appangular/controllers.js"></script>
        <script src="appangular/services.js"></script>


<!--        <script>
            var App = angular.module('filtro', []);
            App.controller('CtrlApp', function ($scope) {
                $scope.nome = 'junao';

            });
            (window.angular);

        </script>-->
    </body>
</html>